# .goreleaser.yml
# Build customization
builds:
  - binary: hcledit
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/egym/hcledit/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
release:
  prerelease: auto
changelog:
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Update README
      - Update CHANGELOG
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
